// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmhlY2R74marpHCTvkEoyp-SwLxhHbZDc',
    appId: '1:619275381651:web:0bbc0ff1fbfdcd56bf9666',
    messagingSenderId: '619275381651',
    projectId: 'gapshap-app-2026',
    authDomain: 'gapshap-app-2026.firebaseapp.com',
    storageBucket: 'gapshap-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz3o1WIgZUwu5wQYQtWAi9saWztgEYTm8',
    appId: '1:619275381651:android:4c8a7a936d6f890fbf9666',
    messagingSenderId: '619275381651',
    projectId: 'gapshap-app-2026',
    storageBucket: 'gapshap-app-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3JDA8PTyIFrsRBjsJ7TTdm4c22czPfNc',
    appId: '1:619275381651:ios:618cd20013860522bf9666',
    messagingSenderId: '619275381651',
    projectId: 'gapshap-app-2026',
    storageBucket: 'gapshap-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.gapshap',
  );
}
