// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqXG4c57omB3UbrJUZEpuSAEppNvLSwvU',
    appId: '1:465805150366:web:0ff8358c819c35a89ad38f',
    messagingSenderId: '465805150366',
    projectId: 'gapshap-app-9901',
    authDomain: 'gapshap-app-9901.firebaseapp.com',
    databaseURL: 'https://gapshap-app-9901-default-rtdb.firebaseio.com',
    storageBucket: 'gapshap-app-9901.firebasestorage.app',
    measurementId: 'G-8E2K3QDXRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfxZfFf_MS1D9JcFbcESKs63jH67fGwxM',
    appId: '1:465805150366:android:5165563c71fb2b5c9ad38f',
    messagingSenderId: '465805150366',
    projectId: 'gapshap-app-9901',
    databaseURL: 'https://gapshap-app-9901-default-rtdb.firebaseio.com',
    storageBucket: 'gapshap-app-9901.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtlxnMttEviAKCLqZ1Ib4qc1DwT0zb4pQ',
    appId: '1:465805150366:ios:f2ac4a6a992698279ad38f',
    messagingSenderId: '465805150366',
    projectId: 'gapshap-app-9901',
    databaseURL: 'https://gapshap-app-9901-default-rtdb.firebaseio.com',
    storageBucket: 'gapshap-app-9901.firebasestorage.app',
    iosClientId: '465805150366-qmi5sgdm9s34db9m6s2lf3m7stgrkqbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gapshap',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtlxnMttEviAKCLqZ1Ib4qc1DwT0zb4pQ',
    appId: '1:465805150366:ios:f2ac4a6a992698279ad38f',
    messagingSenderId: '465805150366',
    projectId: 'gapshap-app-9901',
    databaseURL: 'https://gapshap-app-9901-default-rtdb.firebaseio.com',
    storageBucket: 'gapshap-app-9901.firebasestorage.app',
    iosClientId: '465805150366-qmi5sgdm9s34db9m6s2lf3m7stgrkqbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gapshap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqXG4c57omB3UbrJUZEpuSAEppNvLSwvU',
    appId: '1:465805150366:web:f5967db8c08e8a809ad38f',
    messagingSenderId: '465805150366',
    projectId: 'gapshap-app-9901',
    authDomain: 'gapshap-app-9901.firebaseapp.com',
    databaseURL: 'https://gapshap-app-9901-default-rtdb.firebaseio.com',
    storageBucket: 'gapshap-app-9901.firebasestorage.app',
    measurementId: 'G-REVCDKGL58',
  );
}
